# Action que utiliza get-clima.js para obtener el clima de una ciudad

name: 'Get Clima'
description: 'Obtiene el clima de una ciudad'
inputs:
  ciudad:
    description: 'Nombre de la ciudad'
    required: true
    default: 'Santiago'
  api-key:
    description: 'API Key para WeatherAPI'
    required: true
outputs:
  ciudad:
    description: 'Nombre de la ciudad obtenida'
  clima:
    description: 'Clima actual en grados Celsius'
  fecha:
    description: 'Fecha y hora local de la ciudad'
runs:
  using: 'node12'
  main: 'get-clima.js'