# Action que nos almacena el nombre del usuario que ejecutó el workflow en una variable de entorno llamada USUARIO
name: 'Obtener Usuario'
description: 'Obtiene el nombre del usuario que ejecuta el workflow'
runs:
  using: 'composite'
  steps:
    - run: echo "USUARIO=${{ github.actor }}" >> $GITHUB_ENV
      shell: bash