# Workflow que nos imprime el nombre del usuario que ejecutó el workflow, la fecha, la hora y lo almacena en un archivo llamado visitantes.txt
name: Quién me visita

on: workflow_dispatch

jobs:
    visitante:
        name: Quién me visita
        runs-on: ubuntu-latest
        steps:
            - name: Checkout del repositorio
              uses: actions/checkout@v2

            - name: Listamos los archivos y carpetas
              run: ls -la -R

            - name: Obtener USUARIO de la variable de entorno creada por el action
              uses: ./.github/actions/get-usuario

            - name: Imprimir visitante
              run: echo "El usuario $USUARIO visitó el archivo a las $(date)" >> visitantes.txt
            
            - name: Mostrar visitantes
              run: cat visitantes.txt
            
            - name: Agregar commit con el archivo visitantes.txt
              uses: ./.github/actions/commit-visitantes
              with:
                path: visitantes.txt